sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        MVRy8tRnhf/gyizeZdAjnWCMgg2cztDy2SBj8D42LmFg6ih8H8YeQFezh08fxR4QA2i71YbIXnBEFoUdF2AbE5W3W43IHGfX5GcmXpfsJqVCP9F7ZIvsG7ceSMh6CXl3Qm2hcZdy3nxCjLdluVFk1PvyBi93iW6tnPUORnSXWUVVelTYBEBiWhRbWWGAhdFxSWi5WSsbeXdsKiKx74/JRSvuEKo1KX1UU+xxh8Y8/Ybx4fJIxsGTNDEOK9eI6D8KBybSvxUZnyjnc0Q/tR++14hNeTF2X5bkW2sMT4ntAkHyWQYUXvdomzIIPVDXL8/w2zA7mSTR1By0D90XPopw/u7717uBw+XJTHx+LkZ5l/tHy1Die6O0HW9TJlEGKARBudqnc0Pqv+ksePHCf4rkU5GdDz45jKwGoVfPvrB5yMlZpzdcAOo6BpwD12Gyhilb7aafTaxRx8wR8PWavjkz6oxq62vnMtxfrJCj5lwa5emaHHj901zB6yzGrolWWXpGF+NVNlunSdlTW32IFAez+vcAj4DmPXXykrYXVGmelpZu7DxRRmhDf8nV+/HtxcMXr3BXDxjv8edhSAOQqXB+8TEPWkS2WKsn9D0Rm/up5+K7RJ3W7PiHLOFG0vBYXz/ZnaqsXl/p1h0aZGirefGMdIOLKgJoN7I2mla8JNFhJQ0=
    - secure: >-
        vOQDZzRywzW671RhWYXyGsTyi4gNWICye8al3x0pJVa3W5lqEYf4jEFzyF6GMZxs9P8BBuKsgzNLX+d41bvBN0ZbarMWclGTx1D0t91Svh3JKmndIxBJQoctBqnG/46Hu0Z7TH02078CxszZqELKu57DK1fQm1a7psLQULi6OtnM7cUaXlEtK+5f8xXa99em9Y4UlaCeTH2451ZAtmgtUY5kdCNF2et6od0T9tc6pUT+Xh06YkHZVrcB2nIYL9/oNS154oKcxaR++un3F0K9WdlVqeRCOZsq4JQgW/tyO+kAIkWhpCLSp6AQd9z315USFwQ8xKeUpiY2PLv64lptEh2bWA1a+8DwgdTninIKxxN7VAFb9slr4rC3OlW/aym2SMc03kyrkmf8couGWNcxBMzNori9B2rw1rDM8SB7xtwDF7uOmFchDe7PW+X1q0QGQCiv0xPY14yIA0iMmC03PnLR8KSnysgaieRRl06CEgBROK9YZ3U6nMbYzPx0iA9zUBWRZi1U2Hx+LhoeIhe/iM4WNyx8JWJHiINEenba5kaSl7WPgVJs7YDWKfNjKnFgi3VQZD9xYqjRME/l29s45iU/rB0VPtDdNzOxKr0CwVW0/ORsbVicuh12bXV/O78JRUCl4eWvB2HqxrNjGAu4DemUIUIIL3RojscY3HVbqVo=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
